### ISSUE TITLE
Usage with next-mdx-enhanced

### ISSUE THREAD

**Issue by vvo** [PaulieScanlon/mdx-embed#44]
Hi there, I'd like to use your module with https://github.com/hashicorp/next-mdx-enhanced but have failed for now.

I tried to use MDXEmbedProvider inside a layouts/post.js but always getting the error: Component Tweet was not imported, exported, or provided by MDXProvider as global scope. Any idea on how to make it work? Thanks!

**Comment by PaulieScanlon** [comment]
Hi @vvo We've just released `v0.0.4` i think you were a bit too fast for us.. `v.0.0.1 - v.0.0.3` didn't actually have any components exported we were just testing the lerna publish stuff... give `0.0.4` and try and please do let us know how you get on.

**Comment by vvo** [comment]
Hey there, I still do not know how where to use MDXEmbedProvider when using next-mdx-enhanced. In the end I just used a regular React component inside my mdx code and it worked. This is not a failure of your library, I was just completely lost in mdx/provider :D

**Comment by PaulieScanlon** [comment]
@vvo no worries. We're still a bit unsure about where the `MDXEmbedProvider` should live in a Next app. Probably somewhere near the `MDXProvider` or `MDXRenderer` but having not looked in to this myself yet i don't know. If you do get this working though we'd love to see your repo?

**Comment by elijahmanor** [comment]
@vvo @PaulieScanlon Inside your Layout file you can use the `MDXEmbedProvider` around the `children`

```
import React from "react";
import Head from "next/head";
import { MDXEmbedProvider } from "mdx-embed";

export default function Layout({ children, frontMatter }) {
  const { title } = frontMatter;

  return (
    <div>
      <Head>
        <title>Your Site</title>
      </Head>
      <main>
        <h1>{frontMatter.title}</h1>
        <MDXEmbedProvider>{children}</MDXEmbedProvider>
      </main>
    </div>
  );
}
```

**Comment by PaulieScanlon** [comment]
@molebox FYI
